Repository wtfd-tech/wtfd, pull requests merged in 2019-10, with the labels that each got.

#9 Adminpage
  html/admin.html
  html/footer.html
  html/header.html
  html/index.html
  html/static/admin.js
  html/static/main.js
  internal/orm.go
  internal/server.go
  internal/structs.go
Labels: backend, ui

#12 New Readme
  README.md
  demo.png
Labels: documentation

#29 Add "Release Drafter" action
  .github/release-drafter.yml
  .github/workflows/release-management.yml
Labels: CI

#34 add api.yml for openapi
  api.yml
Labels: Documentation
